# ============================================================
#  INSTITUTIONAL XAUUSD CONFIG
# ============================================================

import os
from dotenv import load_dotenv

# Load environment variables from .env file
_config_dir = os.path.dirname(os.path.abspath(__file__))
_repo_root = os.path.abspath(os.path.join(_config_dir, ".."))
load_dotenv(os.path.join(_repo_root, ".env"))
load_dotenv(os.path.join(_config_dir, ".env"))

# ================= AI =================
CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY", "")
CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-6")
CLAUDE_CHEAP_MODEL = os.getenv("CLAUDE_CHEAP_MODEL", "claude-haiku-4-5-20251001")
CLAUDE_COMPLEX_MODEL = os.getenv("CLAUDE_COMPLEX_MODEL", "claude-sonnet-4-6")
CLAUDE_FALLBACK_MODELS = [
	m.strip() for m in os.getenv(
		"CLAUDE_FALLBACK_MODELS",
		"claude-haiku-4-5-20251001"
	).split(",") if m.strip()
]
ENABLE_CLAUDE = os.getenv("ENABLE_CLAUDE", "false").lower() == "true"
CLAUDE_TIMEOUT_SECS = int(os.getenv("CLAUDE_TIMEOUT_SECS", "30"))
CLAUDE_CALL_COOLDOWN_SECS = int(os.getenv("CLAUDE_CALL_COOLDOWN_SECS", "30"))
CLAUDE_MAX_CONSECUTIVE_FAILURES = int(os.getenv("CLAUDE_MAX_CONSECUTIVE_FAILURES", "3"))
CLAUDE_FAILURE_DISABLE_SECS = int(os.getenv("CLAUDE_FAILURE_DISABLE_SECS", "300"))
CLAUDE_MODEL_LOCKOUT_SECS = int(os.getenv("CLAUDE_MODEL_LOCKOUT_SECS", "600"))
CLAUDE_SESSION_TOKEN_BUDGET = int(os.getenv("CLAUDE_SESSION_TOKEN_BUDGET", "0"))
CLAUDE_ENABLE_SMART_ROUTING = os.getenv("CLAUDE_ENABLE_SMART_ROUTING", "true").lower() == "true"
CLAUDE_AMBER_BUDGET_RATIO = float(os.getenv("CLAUDE_AMBER_BUDGET_RATIO", "0.70"))
CLAUDE_RED_BUDGET_RATIO = float(os.getenv("CLAUDE_RED_BUDGET_RATIO", "0.90"))
CLAUDE_RED_DISABLE_REFINE = os.getenv("CLAUDE_RED_DISABLE_REFINE", "true").lower() == "true"
CLAUDE_COMPLEXITY_THRESHOLD = int(os.getenv("CLAUDE_COMPLEXITY_THRESHOLD", "2"))
CLAUDE_CONTEXT_MAX_TOKENS = int(os.getenv("CLAUDE_CONTEXT_MAX_TOKENS", "150"))
CLAUDE_REFINE_MAX_TOKENS = int(os.getenv("CLAUDE_REFINE_MAX_TOKENS", "60"))
CLAUDE_NEWS_MAX_TOKENS = int(os.getenv("CLAUDE_NEWS_MAX_TOKENS", "180"))
ENABLE_CLAUDE_NEWS_CONTEXT = os.getenv("ENABLE_CLAUDE_NEWS_CONTEXT", "true").lower() == "true"
CLAUDE_ENABLE_PROMPT_CACHING = os.getenv("CLAUDE_ENABLE_PROMPT_CACHING", "true").lower() == "true"
CLAUDE_USAGE_LOG_EVERY_N_CALLS = int(os.getenv("CLAUDE_USAGE_LOG_EVERY_N_CALLS", "10"))
CLAUDE_COST_PER_MILLION_INPUT_SONNET = float(os.getenv("CLAUDE_COST_PER_MILLION_INPUT_SONNET", "3.0"))
CLAUDE_COST_PER_MILLION_OUTPUT_SONNET = float(os.getenv("CLAUDE_COST_PER_MILLION_OUTPUT_SONNET", "15.0"))
CLAUDE_COST_PER_MILLION_INPUT_HAIKU = float(os.getenv("CLAUDE_COST_PER_MILLION_INPUT_HAIKU", "0.8"))
CLAUDE_COST_PER_MILLION_OUTPUT_HAIKU = float(os.getenv("CLAUDE_COST_PER_MILLION_OUTPUT_HAIKU", "4.0"))
CLAUDE_COST_PER_MILLION_INPUT_OPUS = float(os.getenv("CLAUDE_COST_PER_MILLION_INPUT_OPUS", "15.0"))
CLAUDE_COST_PER_MILLION_OUTPUT_OPUS = float(os.getenv("CLAUDE_COST_PER_MILLION_OUTPUT_OPUS", "75.0"))

# ================= MAIN5 DEBUG =================
MAIN5_DEBUG = os.getenv("MAIN5_DEBUG", "false").lower() == "true"
MAIN5_DEBUG_EVERY_SECS = int(os.getenv("MAIN5_DEBUG_EVERY_SECS", "60"))
MAIN5_DEBUG_SIGNAL_ONLY = os.getenv("MAIN5_DEBUG_SIGNAL_ONLY", "false").lower() == "true"

# ================= MAIN6 MODE =================
MAIN6_AUTO_TRADE = os.getenv("MAIN6_AUTO_TRADE", "false").lower() == "true"
MAIN6_SIGNAL_ONLY = os.getenv("MAIN6_SIGNAL_ONLY", "true").lower() == "true"

# ================= TELEGRAM SIGNAL BOT =================
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
TELEGRAM_SIGNAL_BOT_ENABLED = os.getenv("TELEGRAM_SIGNAL_BOT_ENABLED", "true").lower() == "true"
TELEGRAM_PARSE_MODE = os.getenv("TELEGRAM_PARSE_MODE", "HTML")
TELEGRAM_DISABLE_WEB_PAGE_PREVIEW = os.getenv("TELEGRAM_DISABLE_WEB_PAGE_PREVIEW", "true").lower() == "true"
TELEGRAM_SEND_STARTUP_TEST = os.getenv("TELEGRAM_SEND_STARTUP_TEST", "true").lower() == "true"
TELEGRAM_EXECUTION_ALERTS_ENABLED = os.getenv("TELEGRAM_EXECUTION_ALERTS_ENABLED", "true").lower() == "true"
TELEGRAM_EXIT_PROTECTION_ALERTS_ENABLED = os.getenv("TELEGRAM_EXIT_PROTECTION_ALERTS_ENABLED", "true").lower() == "true"

# ================= STARTUP ANALYSIS =================
ENABLE_STARTUP_ANALYSIS = os.getenv("ENABLE_STARTUP_ANALYSIS", "true").lower() == "true"
STARTUP_ANALYSIS_TIMEFRAMES = [
	t.strip() for t in os.getenv("STARTUP_ANALYSIS_TIMEFRAMES", "W1,D1,H4,H1,M15").split(",") if t.strip()
]
STARTUP_ANALYSIS_CANDLES = int(os.getenv("STARTUP_ANALYSIS_CANDLES", "200"))
STRUCTURE_SWING_LOOKBACK = int(os.getenv("STRUCTURE_SWING_LOOKBACK", "60"))
STRUCTURE_MIN_BARS = int(os.getenv("STRUCTURE_MIN_BARS", "80"))
SMC_ANALYSIS_CANDLES = int(os.getenv("SMC_ANALYSIS_CANDLES", "300"))
SMC_MIN_CONFLUENCE_SCORE = int(os.getenv("SMC_MIN_CONFLUENCE_SCORE", "8"))
SMC_ORDER_BLOCK_RANGE = int(os.getenv("SMC_ORDER_BLOCK_RANGE", "25"))
SMC_LIQUIDITY_LENGTH = int(os.getenv("SMC_LIQUIDITY_LENGTH", "14"))
SMC_FVG_THRESHOLD_PERCENT = float(os.getenv("SMC_FVG_THRESHOLD_PERCENT", "0"))
SMC_VOLUME_LOOKBACK = int(os.getenv("SMC_VOLUME_LOOKBACK", "20"))
SMC_VOLUME_SPIKE_MULTIPLIER = float(os.getenv("SMC_VOLUME_SPIKE_MULTIPLIER", "1.5"))

# ================= NEWS FEED =================
NEWS_FEED_ENABLED = os.getenv("NEWS_FEED_ENABLED", "true").lower() == "true"
NEWS_FEED_PROVIDER = os.getenv("NEWS_FEED_PROVIDER", "NEWSAPI")
NEWS_API_KEY = os.getenv("NEWS_API_KEY", "")
NEWS_QUERY = os.getenv("NEWS_QUERY", "XAUUSD OR gold OR Fed OR rates OR inflation")

HIGH_IMPACT_USD_NEWS = [
    "Non-Farm Payrolls", "NFP", "CPI", "Core CPI", "PPI", "FOMC", 
    "Federal Reserve", "Interest Rate", "GDP", "Unemployment Claims", "JOLTS"
]

HIGH_IMPACT_GOLD_NEWS = [
    "Central Bank", "Geopolitical", "War", "Tariff", "US Debt", "Recession"
]

IGNORE_NEWS_COMPLETELY = [
    "Sports", "Entertainment", "Dividend investing", "Crypto", "Individual stock"
]

NEWS_ITEMS = int(os.getenv("NEWS_ITEMS", "6"))
NEWS_LOOKBACK_HOURS = int(os.getenv("NEWS_LOOKBACK_HOURS", "48"))
NEWS_TIMEOUT_SECS = int(os.getenv("NEWS_TIMEOUT_SECS", "12"))
NEWS_ANALYSIS_INTERVAL_MINS = int(os.getenv("NEWS_ANALYSIS_INTERVAL_MINS", "30"))
NEWS_CALENDAR_ENABLED = os.getenv("NEWS_CALENDAR_ENABLED", "false").lower() == "true"
NEWS_CALENDAR_DAYS_AHEAD = int(os.getenv("NEWS_CALENDAR_DAYS_AHEAD", "3"))
NEWS_CALENDAR_ITEMS = int(os.getenv("NEWS_CALENDAR_ITEMS", "4"))

# ================= MARKET =================
SYMBOL = "XAUUSD"
TIMEFRAME = "M15"
CANDLES = 150
ANALYSIS_INTERVAL = 200

# ================= SCORING =================
MIN_SCORE_LONDON_NY = 7
MIN_SCORE_TOKYO = 8
MIN_SCORE_OFFPEAK = 10
SMC_BYPASS_SCORE = 10

# ================= RISK CONTROL =================
MAX_DAILY_LOSS_PERCENT = 2.0
MAX_CONSECUTIVE_LOSSES = 3
MAX_OPEN_TRADES = 2
ENABLE_HIGH_POTENTIAL_SECOND_TRADE = True
MAX_OPEN_TRADES_HIGH_POTENTIAL = 2
HIGH_POTENTIAL_MIN_SCORE = 12
HIGH_POTENTIAL_CONFIDENCE = "HIGH"
BLOCKED_LOG_COOLDOWN_SECS = 30

# ================= TRADE MEMORY & RESTART RESILIENCE =================
# On bot restart, respect the original entry conditions that justified opening the trade
# Only exit structural/exhaustion signals if entry conditions have degraded
ENABLE_TRADE_ENTRY_MEMORY = True
ENTRY_CONDITION_CONFIDENCE_TOLERANCE = 1  # Allow 1 confidence level drop (HIGH->MEDIUM, etc)
ENTRY_CONDITION_SCORE_TOLERANCE = 0.7  # Allow only 70% of original score before exiting

MAX_SPREAD = 20

# ================= EXECUTION =================
AUTO_TRADE = True
MONITOR_INTERVAL = 1
STATUS_PRINT_INTERVAL_SECS = int(os.getenv("STATUS_PRINT_INTERVAL_SECS", "15"))

# ================= SIGNAL MEMORY =================
SIGNAL_COOLDOWN_SECS = int(os.getenv("SIGNAL_COOLDOWN_SECS", "300"))

# ================= DATA VALIDATION =================
DATA_GAP_WARNING_THRESHOLD = float(os.getenv("DATA_GAP_WARNING_THRESHOLD", "0.005"))
DATA_GAP_WARNING_COOLDOWN_SECS = int(os.getenv("DATA_GAP_WARNING_COOLDOWN_SECS", "60"))
DATA_RECOVERY_BACKOFF_SECS = int(os.getenv("DATA_RECOVERY_BACKOFF_SECS", "180"))

# ================= SESSION FILTERS =================
ENABLE_SESSION_FILTERS = os.getenv("ENABLE_SESSION_FILTERS", "true").lower() == "true"
NY_OPEN_TRAP_ENABLED = os.getenv("NY_OPEN_TRAP_ENABLED", "true").lower() == "true"
NY_OPEN_TRAP_START_HOUR = int(os.getenv("NY_OPEN_TRAP_START_HOUR", "12"))
NY_OPEN_TRAP_WINDOW_MINUTES = int(os.getenv("NY_OPEN_TRAP_WINDOW_MINUTES", "30"))
NY_OPEN_STRICT_BLOCK_MINUTES = int(os.getenv("NY_OPEN_STRICT_BLOCK_MINUTES", "30"))
NY_OPEN_REDUCED_RISK_ENABLED = os.getenv("NY_OPEN_REDUCED_RISK_ENABLED", "true").lower() == "true"
NY_OPEN_REDUCED_RISK_MINUTES = int(os.getenv("NY_OPEN_REDUCED_RISK_MINUTES", "30"))
NY_OPEN_REDUCED_RISK_MULTIPLIER = float(os.getenv("NY_OPEN_REDUCED_RISK_MULTIPLIER", "0.5"))
NY_OPEN_BLOCK_START_HOUR = int(os.getenv("NY_OPEN_BLOCK_START_HOUR", "15"))
NY_OPEN_BLOCK_START_MINUTE = int(os.getenv("NY_OPEN_BLOCK_START_MINUTE", "30"))
NY_OPEN_BLOCK_DURATION_MINUTES = int(os.getenv("NY_OPEN_BLOCK_DURATION_MINUTES", "30"))
SESSION_OPEN_CLOSE_FILTER_ENABLED = os.getenv("SESSION_OPEN_CLOSE_FILTER_ENABLED", "true").lower() == "true"
LONDON_OPEN_SKIP_MINUTES = int(os.getenv("LONDON_OPEN_SKIP_MINUTES", "15"))
NY_OPEN_SKIP_MINUTES = int(os.getenv("NY_OPEN_SKIP_MINUTES", "15"))
TOKYO_OPEN_SKIP_MINUTES = int(os.getenv("TOKYO_OPEN_SKIP_MINUTES", "15"))
LONDON_CLOSE_SKIP_MINUTES = int(os.getenv("LONDON_CLOSE_SKIP_MINUTES", "15"))
NY_CLOSE_SKIP_MINUTES = int(os.getenv("NY_CLOSE_SKIP_MINUTES", "15"))
TOKYO_CLOSE_SKIP_MINUTES = int(os.getenv("TOKYO_CLOSE_SKIP_MINUTES", "15"))
SESSION_FILTER_TIME_REFERENCE = os.getenv("SESSION_FILTER_TIME_REFERENCE", "LOCAL")
SESSION_FILTER_UTC_OFFSET_HOURS = int(os.getenv("SESSION_FILTER_UTC_OFFSET_HOURS", "0"))
FRIDAY_RISK_REDUCTION_ENABLED = os.getenv("FRIDAY_RISK_REDUCTION_ENABLED", "true").lower() == "true"
FRIDAY_RISK_REDUCTION_HOUR = int(os.getenv("FRIDAY_RISK_REDUCTION_HOUR", "14"))
FRIDAY_RISK_MULTIPLIER = float(os.getenv("FRIDAY_RISK_MULTIPLIER", "0.5"))
DEAD_MARKET_FILTER_ENABLED = os.getenv("DEAD_MARKET_FILTER_ENABLED", "true").lower() == "true"
DEAD_MARKET_START_HOUR = int(os.getenv("DEAD_MARKET_START_HOUR", "22"))
DEAD_MARKET_END_HOUR = int(os.getenv("DEAD_MARKET_END_HOUR", "2"))

# ================= CORRELATION WEIGHTING =================
ENABLE_CORRELATION_FRAMEWORK = os.getenv("ENABLE_CORRELATION_FRAMEWORK", "true").lower() == "true"
CORRELATION_WEIGHT = float(os.getenv("CORRELATION_WEIGHT", "0.7"))
CORRELATION_MAX_ABS_SCORE = int(os.getenv("CORRELATION_MAX_ABS_SCORE", "3"))
RETAIL_LONG_RATIO_THRESHOLD = float(os.getenv("RETAIL_LONG_RATIO_THRESHOLD", "70"))
CORRELATION_DXY_TREND = os.getenv("CORRELATION_DXY_TREND", "UNKNOWN")
CORRELATION_YIELDS_TREND = os.getenv("CORRELATION_YIELDS_TREND", "UNKNOWN")
ENABLE_YIELDS_CONTEXT = os.getenv("ENABLE_YIELDS_CONTEXT", "false").lower() == "true"
ENABLE_YIELDS_CORRELATION = os.getenv("ENABLE_YIELDS_CORRELATION", "false").lower() == "true"
CORRELATION_SILVER_TREND = os.getenv("CORRELATION_SILVER_TREND", "UNKNOWN")
CORRELATION_RETAIL_LONG_RATIO = float(os.getenv("CORRELATION_RETAIL_LONG_RATIO", "0"))
DUPLICATE_SIGNAL_WINDOW_MINUTES = float(os.getenv("DUPLICATE_SIGNAL_WINDOW_MINUTES", "15"))
DUPLICATE_ENTRY_THRESHOLD = float(os.getenv("DUPLICATE_ENTRY_THRESHOLD", "0.5"))
SCORE_BUCKET_SIZE = int(os.getenv("SCORE_BUCKET_SIZE", "2"))
# PHASE 4: Lowered execution score floor from 8 to 6.5 for more trade participation
MIN_SIGNAL_SCORE_EXECUTION = float(os.getenv("MIN_SIGNAL_SCORE_EXECUTION", "6.5"))
MIN_SIGNAL_SCORE_TELEGRAM = float(os.getenv("MIN_SIGNAL_SCORE_TELEGRAM", "6.5"))
EXECUTION_BUY_MIN_SCORE = float(os.getenv("EXECUTION_BUY_MIN_SCORE", "6"))
EXECUTION_SELL_MAX_SCORE = float(os.getenv("EXECUTION_SELL_MAX_SCORE", "-6"))
FULL_CONFIDENCE_SCORE = float(os.getenv("FULL_CONFIDENCE_SCORE", "10"))
MODERATE_CONFIDENCE_RISK_MULTIPLIER = float(os.getenv("MODERATE_CONFIDENCE_RISK_MULTIPLIER", "0.7"))
MODERATE_TRADE_MIN_SCORE = float(os.getenv("MODERATE_TRADE_MIN_SCORE", "8"))
MODERATE_TRADE_MAX_SCORE = float(os.getenv("MODERATE_TRADE_MAX_SCORE", "10"))
MODERATE_TRADE_RISK_MULTIPLIER = float(os.getenv("MODERATE_TRADE_RISK_MULTIPLIER", "0.7"))
ENABLE_MOMENTUM_OVERRIDE = os.getenv("ENABLE_MOMENTUM_OVERRIDE", "true").lower() == "true"
MOMENTUM_OVERRIDE_MIN_SCORE = float(os.getenv("MOMENTUM_OVERRIDE_MIN_SCORE", "8"))
MOMENTUM_OVERRIDE_RISK_MULTIPLIER = float(os.getenv("MOMENTUM_OVERRIDE_RISK_MULTIPLIER", "0.7"))
MIN_CONFIDENCE_EXECUTION = os.getenv("MIN_CONFIDENCE_EXECUTION", "HIGH")
MIN_CONFIDENCE_TELEGRAM = os.getenv("MIN_CONFIDENCE_TELEGRAM", "MEDIUM")

# ================= DIRECTIONAL COOLDOWN =================
DIRECTIONAL_COOLDOWN_ENABLED = os.getenv("DIRECTIONAL_COOLDOWN_ENABLED", "true").lower() == "true"
DIRECTIONAL_COOLDOWN_DEFAULT_MINUTES = float(os.getenv("DIRECTIONAL_COOLDOWN_DEFAULT_MINUTES", "15"))
DIRECTIONAL_COOLDOWN_LOSS_MINUTES = float(os.getenv("DIRECTIONAL_COOLDOWN_LOSS_MINUTES", "25"))
DIRECTIONAL_COOLDOWN_WIN_MIN_MINUTES = float(os.getenv("DIRECTIONAL_COOLDOWN_WIN_MIN_MINUTES", "5"))
DIRECTIONAL_COOLDOWN_WIN_MAX_MINUTES = float(os.getenv("DIRECTIONAL_COOLDOWN_WIN_MAX_MINUTES", "10"))
SAME_DIRECTION_COOLDOWN_AFTER_CLOSE_MINUTES = float(os.getenv("SAME_DIRECTION_COOLDOWN_AFTER_CLOSE_MINUTES", "20"))
COOLDOWN_CONDITIONAL_CORRELATION_MIN = float(os.getenv("COOLDOWN_CONDITIONAL_CORRELATION_MIN", "2"))
COOLDOWN_BYPASS_MIN_SCORE = float(os.getenv("COOLDOWN_BYPASS_MIN_SCORE", "15"))

# ================= DXY CORRELATION (MT5: UsDollar) =================
ENABLE_DXY_CORRELATION = os.getenv("ENABLE_DXY_CORRELATION", "true").lower() == "true"
DXY_SYMBOL = os.getenv("DXY_SYMBOL", "UsDollar")
DXY_WEIGHT = float(os.getenv("DXY_WEIGHT", "2.0"))
DXY_EMA_FAST = int(os.getenv("DXY_EMA_FAST", "10"))
DXY_EMA_SLOW = int(os.getenv("DXY_EMA_SLOW", "30"))
DXY_LOOKBACK_CANDLES = int(os.getenv("DXY_LOOKBACK_CANDLES", "80"))

# ================= SILVER CORRELATION (MT5: XAGUSD) =================
ENABLE_SILVER_CORRELATION = os.getenv("ENABLE_SILVER_CORRELATION", "true").lower() == "true"
SILVER_SYMBOL = os.getenv("SILVER_SYMBOL", "XAGUSD")
SILVER_WEIGHT = float(os.getenv("SILVER_WEIGHT", "1.5"))
SILVER_EMA_FAST = int(os.getenv("SILVER_EMA_FAST", "10"))
SILVER_EMA_SLOW = int(os.getenv("SILVER_EMA_SLOW", "30"))
SILVER_LOOKBACK_CANDLES = int(os.getenv("SILVER_LOOKBACK_CANDLES", "80"))
SILVER_MOMENTUM_THRESHOLD_PCT = float(os.getenv("SILVER_MOMENTUM_THRESHOLD_PCT", "0.05"))
SILVER_MOMENTUM_BONUS = float(os.getenv("SILVER_MOMENTUM_BONUS", "0.5"))

# ================= ADAPTIVE LEARNING =================
ENABLE_TRADE_JOURNAL = os.getenv("ENABLE_TRADE_JOURNAL", "true").lower() == "true"
JOURNAL_MIN_TRADES_FOR_ADAPTATION = int(os.getenv("JOURNAL_MIN_TRADES_FOR_ADAPTATION", "5"))
JOURNAL_LOW_WINRATE_THRESHOLD = float(os.getenv("JOURNAL_LOW_WINRATE_THRESHOLD", "40"))
JOURNAL_HIGH_WINRATE_THRESHOLD = float(os.getenv("JOURNAL_HIGH_WINRATE_THRESHOLD", "60"))
JOURNAL_SCORE_PENALTY = float(os.getenv("JOURNAL_SCORE_PENALTY", "-1.5"))
JOURNAL_SCORE_BONUS = float(os.getenv("JOURNAL_SCORE_BONUS", "1.0"))
SETUP_WINRATE_REJECTION_THRESHOLD = float(os.getenv("SETUP_WINRATE_REJECTION_THRESHOLD", "0.30"))
SETUP_WINRATE_MIN_TRADES = int(os.getenv("SETUP_WINRATE_MIN_TRADES", "8"))
SETUP_WINRATE_STRONG_SCORE_OVERRIDE = float(os.getenv("SETUP_WINRATE_STRONG_SCORE_OVERRIDE", "16.0"))
SETUP_WINRATE_STRONG_MOMENTUM_OVERRIDE = float(os.getenv("SETUP_WINRATE_STRONG_MOMENTUM_OVERRIDE", "2.5"))
SETUP_WINRATE_OVERRIDE_MIN_CORRELATION_MOMENTUM = float(os.getenv("SETUP_WINRATE_OVERRIDE_MIN_CORRELATION_MOMENTUM", "0.25"))
SETUP_WINRATE_OVERRIDE_RISK_MULTIPLIER = float(os.getenv("SETUP_WINRATE_OVERRIDE_RISK_MULTIPLIER", "0.75"))
SETUP_WINRATE_SOFT_SCORE_PENALTY = float(os.getenv("SETUP_WINRATE_SOFT_SCORE_PENALTY", "2.0"))
SETUP_WINRATE_SOFT_RISK_MULTIPLIER = float(os.getenv("SETUP_WINRATE_SOFT_RISK_MULTIPLIER", "0.5"))
SETUP_WINRATE_SOFT_CONFIDENCE = os.getenv("SETUP_WINRATE_SOFT_CONFIDENCE", "MEDIUM")
REGIME_RECENT_CHANGE_RISK_MULTIPLIER = float(os.getenv("REGIME_RECENT_CHANGE_RISK_MULTIPLIER", "0.75"))
REGIME_RECENT_CHANGE_CONFIDENCE = os.getenv("REGIME_RECENT_CHANGE_CONFIDENCE", "MEDIUM")
CORRELATION_MOMENTUM_MIN_THRESHOLD = float(os.getenv("CORRELATION_MOMENTUM_MIN_THRESHOLD", "0.03"))

# ================= DYNAMIC RISK MODEL =================
ENABLE_DYNAMIC_RISK_MODEL = os.getenv("ENABLE_DYNAMIC_RISK_MODEL", "true").lower() == "true"
RISK_MULTIPLIER_HIGH_CONFIDENCE = float(os.getenv("RISK_MULTIPLIER_HIGH_CONFIDENCE", "1.0"))
RISK_MULTIPLIER_MEDIUM_CONFIDENCE = float(os.getenv("RISK_MULTIPLIER_MEDIUM_CONFIDENCE", "0.5"))
RISK_MULTIPLIER_LOW_CONFIDENCE = float(os.getenv("RISK_MULTIPLIER_LOW_CONFIDENCE", "0.0"))
DRAWDOWN_RISK_REDUCTION_THRESHOLD = float(os.getenv("DRAWDOWN_RISK_REDUCTION_THRESHOLD", "5.0"))
DRAWDOWN_RISK_REDUCTION_MULTIPLIER = float(os.getenv("DRAWDOWN_RISK_REDUCTION_MULTIPLIER", "0.5"))
CORRELATION_RISK_THRESHOLD = float(os.getenv("CORRELATION_RISK_THRESHOLD", "2.0"))
CORRELATION_RISK_UP_MULTIPLIER = float(os.getenv("CORRELATION_RISK_UP_MULTIPLIER", "1.2"))
CORRELATION_RISK_DOWN_MULTIPLIER = float(os.getenv("CORRELATION_RISK_DOWN_MULTIPLIER", "0.7"))
CORRELATION_HARD_BLOCK_SCORE = float(os.getenv("CORRELATION_HARD_BLOCK_SCORE", "-3.0"))
CORRELATION_REDUCED_RISK_SCORE = float(os.getenv("CORRELATION_REDUCED_RISK_SCORE", "-2.0"))
CORRELATION_REDUCED_RISK_MULTIPLIER = float(os.getenv("CORRELATION_REDUCED_RISK_MULTIPLIER", "0.5"))
MAX_RISK_MULTIPLIER = float(os.getenv("MAX_RISK_MULTIPLIER", "1.5"))
MIN_RISK_MULTIPLIER = float(os.getenv("MIN_RISK_MULTIPLIER", "0.0"))

# ================= REGIME FILTER =================
ENABLE_REGIME_FILTER = True
ALLOW_TRANSITION_SCALP = True
REGIME_LOG_COOLDOWN = 30
ENABLE_REGIME_STABILITY_CONFIRMATION = os.getenv("ENABLE_REGIME_STABILITY_CONFIRMATION", "true").lower() == "true"

# ================= SL / TP =================
SL_ATR_MULTIPLIER = 1.5
TP_RR_HIGH = 3.0
TP_RR_MEDIUM = 2.0

# ================= SCALP-SPECIFIC SL / TP =================
SCALP_SL_ATR_MULTIPLIER = 0.8  # Tighter SL for scalp trades
SCALP_TP_RR = 1.0  # 1:1 risk-reward ratio for scalps (quick in-out)
INSTITUTIONAL_SL_ATR_MULTIPLIER = 1.5  # Larger SL for institutional trades
INSTITUTIONAL_TP_RR_HIGH = 3.0  # 3:1 for high confidence institutional
INSTITUTIONAL_TP_RR_MEDIUM = 2.0  # 2:1 for medium confidence institutional

# ================= TRADE STRATEGY DETERMINATION =================
ENABLE_TRADE_STRATEGY_LABEL = True  # Label trades as SCALP or INSTITUTIONAL
SCALP_REGIME_TYPES = ["HIGH_VOL", "RANGE"]  # Regimes that favor scalping
INSTITUTIONAL_REGIME_TYPES = ["TREND", "HIGH_VOL"]  # Regimes that favor institutional trades
SCALP_MIN_SCORE = 8.0  # Minimum score to classify as scalp (if in scalp regime)
INSTITUTIONAL_MIN_SCORE = 10.0  # Minimum score to classify as institutional (if in institutional regime)

# PHASE 7: RR Validation before order send
MIN_RR_RATIO = float(os.getenv("MIN_RR_RATIO", "1.5"))  # Minimum reward-to-risk ratio (reward / risk)
ENABLE_RR_VALIDATION = os.getenv("ENABLE_RR_VALIDATION", "true").lower() == "true"
ENABLE_AUTO_TP_ADJUSTMENT = os.getenv("ENABLE_AUTO_TP_ADJUSTMENT", "false").lower() == "true"

# ================= HTF CONFLICT SOFT PENALTY =================
HTF_CONFLICT_SCORE_PENALTY = float(os.getenv("HTF_CONFLICT_SCORE_PENALTY", "0.7"))
HTF_CONFLICT_RISK_PENALTY = float(os.getenv("HTF_CONFLICT_RISK_PENALTY", "0.5"))
HTF_CONFLICT_TP_PENALTY = float(os.getenv("HTF_CONFLICT_TP_PENALTY", "0.7"))
HTF_CONFLICT_STRONG_OVERRIDE_THRESHOLD = float(os.getenv("HTF_CONFLICT_STRONG_OVERRIDE_THRESHOLD", "12"))

# ================= DYNAMIC SL MANAGEMENT =================
ENABLE_BREAKEVEN = True
ENABLE_PROFIT_LOCK = True
ENABLE_TRAILING_STOP = True
BREAKEVEN_THRESHOLD = 0.5  # 0.5R profit triggers breakeven move
PROFIT_LOCK_1R_THRESHOLD = 1.0  # At 1R, move SL to +0.5R
PROFIT_LOCK_2R_THRESHOLD = 2.0  # At 2R, move SL to +1R
TRAILING_STOP_MODE = "CANDLE_LOW"  # Use candle high/low for trail
SL_MOVE_CHECK_INTERVAL = 15  # Check SL every N iterations
MIN_HOLD_MINUTES = float(os.getenv("MIN_HOLD_MINUTES", "4"))
BREAKEVEN_R_THRESHOLD = float(os.getenv("BREAKEVEN_R_THRESHOLD", "0.5"))
TRAILING_START_R = float(os.getenv("TRAILING_START_R", "1.0"))
TRAILING_ATR_MULTIPLIER = float(os.getenv("TRAILING_ATR_MULTIPLIER", "1.0"))
MIN_EARLY_EXIT_PROFIT_R = float(os.getenv("MIN_EARLY_EXIT_PROFIT_R", "0.25"))
MOMENTUM_FLIP_PROTECT_MIN_PROFIT_R = float(os.getenv("MOMENTUM_FLIP_PROTECT_MIN_PROFIT_R", "0.3"))
MOMENTUM_FLIP_PROTECT_LOCK_R = float(os.getenv("MOMENTUM_FLIP_PROTECT_LOCK_R", "0.1"))

# ================= SESSION TIMES =================
LONDON_START, LONDON_END = 7, 16
NY_START, NY_END = 12, 23
TOKYO_START, TOKYO_END = 0, 9

# ================= TREND FATIGUE / LATE ENTRY =================
ENABLE_TREND_FATIGUE_FILTER = os.getenv("ENABLE_TREND_FATIGUE_FILTER", "true").lower() == "true"
MAX_CONSECUTIVE_TRADES_PER_DIRECTION = int(os.getenv("MAX_CONSECUTIVE_TRADES_PER_DIRECTION", "3"))
REQUIRE_PULLBACK_FOR_REENTRY = os.getenv("REQUIRE_PULLBACK_FOR_REENTRY", "true").lower() == "true"
TREND_FATIGUE_SOFT_MODE = os.getenv("TREND_FATIGUE_SOFT_MODE", "true").lower() == "true"  # PHASE 2: Enabled by default
TREND_FATIGUE_REDUCTION_MULTIPLIER = float(os.getenv("TREND_FATIGUE_REDUCTION_MULTIPLIER", "0.7"))
ENABLE_LATE_ENTRY_FILTER = os.getenv("ENABLE_LATE_ENTRY_FILTER", "true").lower() == "true"
RSI_OVERBOUGHT_THRESHOLD = float(os.getenv("RSI_OVERBOUGHT_THRESHOLD", "70"))
RSI_OVERSOLD_THRESHOLD = float(os.getenv("RSI_OVERSOLD_THRESHOLD", "30"))
MAX_DISTANCE_FROM_EMA_ATR = float(os.getenv("MAX_DISTANCE_FROM_EMA_ATR", "1.5"))
MOMENTUM_WEAKENING_PENALTY = float(os.getenv("MOMENTUM_WEAKENING_PENALTY", "-1.5"))
LATE_ENTRY_CORRELATION_BOOST_THRESHOLD = float(os.getenv("LATE_ENTRY_CORRELATION_BOOST_THRESHOLD", "2.0"))
LATE_ENTRY_RISK_REDUCTION_MULTIPLIER = float(os.getenv("LATE_ENTRY_RISK_REDUCTION_MULTIPLIER", "0.7"))

# ================= PHASE 2: SOFT MOMENTUM PENALTIES =================
MOMENTUM_SOFT_PENALTY = float(os.getenv("MOMENTUM_SOFT_PENALTY", "1.0"))  # Score penalty for weak momentum
MOMENTUM_SOFT_RISK_MULTIPLIER = float(os.getenv("MOMENTUM_SOFT_RISK_MULTIPLIER", "0.8"))  # Risk reduction for weak momentum
CORRELATION_MOMENTUM_SOFT_THRESHOLD = float(os.getenv("CORRELATION_MOMENTUM_SOFT_THRESHOLD", "0.015"))  # Soft below this
CORRELATION_MOMENTUM_SOFT_PENALTY = float(os.getenv("CORRELATION_MOMENTUM_SOFT_PENALTY", "0.75"))  # Score penalty

# ================= PHASE 4: LOWERED CORRELATION MOMENTUM THRESHOLDS =================
CORRELATION_MOMENTUM_MIN_THRESHOLD = float(os.getenv("CORRELATION_MOMENTUM_MIN_THRESHOLD", "0.020"))  # Lowered from 0.03
CORRELATION_MOMENTUM_HARD_FLOOR = float(os.getenv("CORRELATION_MOMENTUM_HARD_FLOOR", "0.010"))  # Below this = hard reject

# ================= PHASE 5: LOW CONFIDENCE SOFT MODE =================
ENABLE_LOW_CONFIDENCE_MODE = os.getenv("ENABLE_LOW_CONFIDENCE_MODE", "true").lower() == "true"
LOW_CONFIDENCE_RISK_MULTIPLIER = float(os.getenv("LOW_CONFIDENCE_RISK_MULTIPLIER", "0.5"))  # Reduced lot size
LOW_CONFIDENCE_SCORE_PENALTY = float(os.getenv("LOW_CONFIDENCE_SCORE_PENALTY", "1.0"))  # Additional score penalty

ENABLE_TELEGRAM_REJECTION_DEBUG = os.getenv("ENABLE_TELEGRAM_REJECTION_DEBUG", "false").lower() == "true"
ENABLE_DECISION_VALIDATION_DEBUG = os.getenv("ENABLE_DECISION_VALIDATION_DEBUG", "true").lower() == "true"

TRADE_SESSION_START = 0
TRADE_SESSION_END = 23

# ================= TRADE DURATION =================
TRADE_DURATION_MODE = "SHORT"
MAX_TRADE_DURATION_SHORT = 1
MAX_TRADE_DURATION_LONG = 5

# ================= EXIT ENGINE =================
EXIT_GRACE_PERIOD = 300
EXIT_SIGNAL_COOLDOWN = 300
EXIT_URGENCY_THRESHOLD = 3

# ================= SCALPING =================
SCALP_MODE = True
SCALP_PROFIT_TARGET = 50
SCALP_MAX_LOSS = 8
SCALP_MIN_HOLD_SECS = 20
SCALP_MAX_HOLD_SECS = 120
SCALP_MAX_TRADES = 2
SCALP_REENTER = True
SCALP_COOLDOWN_SECS = 30
SCALP_REVALIDATE = True
SCALP_MIN_VOLUME_RATIO = 0.6
SCALP_MAX_SPREAD = 5

# ================= SAFETY =================
ENABLE_CIRCUIT_BREAKER = True
PAUSE_AFTER_DRAWDOWN = 5.0   # %

# ================= LOGGING =================
LOG_TRADES_TO_FILE = True
LOG_FILE = "logs/trades.log"

# ================= INSTITUTIONAL MODE =================
USE_INSTITUTIONAL_STRATEGY = True
INSTITUTIONAL_ENTRY_THRESHOLD = float(os.getenv("INSTITUTIONAL_ENTRY_THRESHOLD", "8"))
INSTITUTIONAL_MEDIUM_CONFIDENCE = float(os.getenv("INSTITUTIONAL_MEDIUM_CONFIDENCE", "5"))
INSTITUTIONAL_HIGH_CONFIDENCE = float(os.getenv("INSTITUTIONAL_HIGH_CONFIDENCE", "8"))

# ================= REGIME AWARENESS =================
ENABLE_REGIME_FILTER = True
STRATEGY_TYPE = "scalp"  # scalp, swing, trend

# ================= EXECUTION VALIDATION =================
ENABLE_EXECUTION_VALIDATION = True
ENABLE_DATA_VALIDATION = True
MAX_SLIPPAGE_PIPS = 2
REQUIRE_FILL_CONFIRMATION = True

# ================= STATE MANAGEMENT =================
ENABLE_STATE_PERSISTENCE = True
STATE_FILE = "data/bot_state.json"

# ================= ADVANCED POSITION SIZING =================
USE_CONFIDENCE_WEIGHTING = True
BASE_LOT_SIZE = 0.1
CONFIDENCE_LOT_MULTIPLIER = 1.5  # Scale up with confidence
ENABLE_ATR_POSITION_SIZING = os.getenv("ENABLE_ATR_POSITION_SIZING", "true").lower() == "true"
RISK_PER_TRADE_PERCENT = float(os.getenv("RISK_PER_TRADE_PERCENT", "1.0"))
MIN_RISK_PER_TRADE_PERCENT = float(os.getenv("MIN_RISK_PER_TRADE_PERCENT", "0.1"))
MAX_RISK_PER_TRADE_PERCENT = float(os.getenv("MAX_RISK_PER_TRADE_PERCENT", "1.5"))

# ================= MAIN5 SETTINGS (5m CHoCH -> 1m Engulfing) =================
MAIN5_TIMEFRAME_HIGH = os.getenv("MAIN5_TIMEFRAME_HIGH", "M5")
MAIN5_TIMEFRAME_LOW = os.getenv("MAIN5_TIMEFRAME_LOW", "M1")
MAIN5_TIMEFRAME_OB = os.getenv("MAIN5_TIMEFRAME_OB", "M15")
MAIN5_HIGH_CANDLES = int(os.getenv("MAIN5_HIGH_CANDLES", "200"))
MAIN5_LOW_CANDLES = int(os.getenv("MAIN5_LOW_CANDLES", "400"))
MAIN5_OB_CANDLES = int(os.getenv("MAIN5_OB_CANDLES", "200"))
MAIN5_CHOCH_LOOKBACK = int(os.getenv("MAIN5_CHOCH_LOOKBACK", "40"))
MAIN5_SWING_LEFT = int(os.getenv("MAIN5_SWING_LEFT", "2"))
MAIN5_SWING_RIGHT = int(os.getenv("MAIN5_SWING_RIGHT", "2"))
MAIN5_RETEST_LOOKBACK_LTF = int(os.getenv("MAIN5_RETEST_LOOKBACK_LTF", "6"))
MAIN5_FVG_LOOKBACK = int(os.getenv("MAIN5_FVG_LOOKBACK", "60"))
MAIN5_SIGNAL_COOLDOWN_SECS = int(os.getenv("MAIN5_SIGNAL_COOLDOWN_SECS", "120"))
MAIN5_OB_LOOKBACK = int(os.getenv("MAIN5_OB_LOOKBACK", "80"))
MAIN5_OB_MAX_AGE = int(os.getenv("MAIN5_OB_MAX_AGE", "40"))
MAIN5_TELEGRAM_ALERTS_ENABLED = os.getenv("MAIN5_TELEGRAM_ALERTS_ENABLED", "true").lower() == "true"
MAIN5_HTF_TIMEFRAMES = os.getenv("MAIN5_HTF_TIMEFRAMES", "D1,H4,H1")
MAIN5_HTF_CANDLES = int(os.getenv("MAIN5_HTF_CANDLES", "200"))
MAIN5_HTF_LOOKBACK = int(os.getenv("MAIN5_HTF_LOOKBACK", "80"))
MAIN5_HTF_SCORE_BOOST = float(os.getenv("MAIN5_HTF_SCORE_BOOST", "0.5"))
MAIN5_LTF_CONFIRM_BOOST = float(os.getenv("MAIN5_LTF_CONFIRM_BOOST", "0.5"))
MAIN5_TP_SOURCE = os.getenv("MAIN5_TP_SOURCE", "M5")
MAIN5_TP_LOOKBACK = int(os.getenv("MAIN5_TP_LOOKBACK", "60"))

# ================= DRAWDOWN PROTECTION =================
ENABLE_CIRCUIT_BREAKER = True
DAILY_LOSS_CIRCUIT_PERCENT = 3.0
WEEKLY_LOSS_CIRCUIT_PERCENT = 8.0
